"""update comment reply tables

Revision ID: 2af14b09ed0c
Revises: dd4b28de9103
Create Date: 2022-12-22 13:24:14.999578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af14b09ed0c'
down_revision = 'dd4b28de9103'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_replies', sa.Column('body', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment_replies', 'body')
    # ### end Alembic commands ###
