"""add post_id to comments table

Revision ID: 874edba220b1
Revises: d78a50b44270
Create Date: 2022-10-02 19:19:21.029000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874edba220b1'
down_revision = 'd78a50b44270'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('post_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'post_id')
    # ### end Alembic commands ###
