"""update comment reply tabless

Revision ID: 8961c13fd049
Revises: 2af14b09ed0c
Create Date: 2022-12-22 13:39:25.524112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8961c13fd049'
down_revision = '2af14b09ed0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_replies', sa.Column('approved', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment_replies', 'approved')
    # ### end Alembic commands ###
